### PR TITLE
re-implement the `repr`

### PR DESCRIPTION
**Pull request by keewis**
This makes use of the `numpy.ndarray` `repr`, so to be fully independent we'd also have to reimplement our own array formatting, but for now this doesn't use `numpy.ma.MaskedArray`'s `repr`.

Edit: I guess that's only slightly better than relying on `numpy.ma.MaskedArray`'s `repr`, we still rely on `numpy`, so we wouldn't be able to get rid of the dependency on that. Also, not all Array API-compliant arrays support string dtypes (as that's not required)?

`_repr_inline_` is a special method that is used by `xarray` and which returns a shortened one-line `repr` without the shape and dtype.

So far there are only tests for the data `repr` (`MaskedArray.__str__`), I will add the tests for `__repr__` later (so don't merge before that).

### CODE REVIEW

**Comment by keewis** [comment]
by the way, do you mind if I set up CI and `pre-commit` hooks?

**Comment by mdhaber** [comment]
> by the way, do you mind if I set up CI and pre-commit hooks?

Please!

**Comment by mdhaber** [comment]
But please not Black : / Can you live without it?

**Comment by mdhaber** [comment]
> Edit: I guess that's only slightly better than relying on `numpy.ma.MaskedArray`'s `repr`, we still rely on `numpy`, so we wouldn't be able to get rid of the dependency on that. Also, not all Array API-compliant arrays support string dtypes (as that's not required)?

Yeah, I don't really see a need to rewrite this if it still relies on NumPy. I was trying to avoid the NumPy dependency. What I had in mind was adding a layer on top of the `__repr__` or `__str__` of the underlying array library with regular expressions or something.

**Comment by keewis** [comment]
If you look at the most recent commits you'll see that this almost reimplements `numpy`'s `repr`, but without depending on it (instead, it uses slicing and iterating over smaller subsets). It also makes sure to not format everything (which could take very long). The only thing that we would miss is the wrapped array type.

If that's an issue we can go with formatting data and mask separately (which is very easy).

Using a regex to modify the wrapped array's `repr` might be fragile since the `repr` is not standardized.

**Comment by mdhaber** [comment]
> Using a regex to modify the wrapped array's repr might be fragile since the repr is not standardized

Of course, but personally, I'd only intend for it to be robust for libraries that are used. If it's much simpler, I'd be comfortable with something that breaks with hypothetical libraries or libraries that nobody needs to wrap with `marray`. We can always fall back to representing the two arrays separately if something goes wrong.

I'll take a closer look at what's here, though. If it strikes the right balance of simplicity and robustness, sounds good to me!

**Comment by mdhaber** [comment]
I might just test and merge this if you're happy with it, but I thought I'd throw an option out there that I think would be quite concise and would respect the array library's format (e.g. `np.set_printoptions`) for representing arrays under pretty mild assumptions. (It's terribly inefficient, but I put a really big weight on code simplicity.)
- Replace all zeros in floating point arrays with +0 and replace masked values with -0. Replace -0s in the array's `__repr__` or `__str__` string with `----` of the appropriate length - the same number of characters as the match. (It should be easy to find a regular expression that reliably matches negative zeros, regardless of how they are formatted like. I doubt anyone is going to notice or complain that the distinction between +/- 0 is lost.)
- Upcast boolean arrays to `uint16`, representing `True`, `False`, and masked values with different four-digit sentinel values. Find and replace those sentinel values in the string as appropriate.
- Upcast integer data arrays to `int64`, replacing masked values with any sentinel value that is not in the array (e.g. the maximum plus 1, if it doesn't overflow). Replace sentinel values in the array's string with `----` of the appropriate number of digits. (It's easy to find the sentinel values in the string because there is no variety in how integers are included in the string - all digits are always shown, I think.)

**Comment by mdhaber** [comment]
For this code:

<details>

```python3
import numpy as np
import marray
mxp = marray.get_namespace(np)
data = np.asarray([[ 10.145273  ,   0.        ,  10.543168  ,  10.06865   ,          4.89986   ,  12.200225  ,   3.9135966 ,   1.306433  ],       [ 10.602975  ,   0.        ,  -1.5708277 ,   0.        ,         -6.0110965 ,  -2.1144137 ,  13.986411  ,   0.52917767],       [-12.671135  ,   6.484597  ,  -7.1020255 , -10.702476  ,          0.        ,   0.        ,   9.679424  ,  -2.5499823 ],       [  0.        ,   0.        ,  -5.3532686 ,   0.        ,          0.        ,  -1.7456701 , -21.932783  ,   2.6757898 ],       [ -5.968359  , -12.241867  ,   0.        ,  -2.3720222 ,          0.        ,   0.        ,   0.        ,   0.13664268],       [-15.532685  ,   2.4078274 ,   6.282031  ,   0.        ,          7.5855317 ,  20.759636  ,   0.        ,  15.117776  ],       [  0.        ,   6.4898    ,  -0.9861215 ,   6.929004  ,         -7.7859383 ,   0.        ,   0.        ,  -7.2034793 ],       [ 20.820364  ,   0.        ,  -9.436462  ,  -0.99235004,          8.174761  ,   0.        ,   0.        ,   0.        ],       [ -3.9510887 ,   0.        ,  -7.876617  ,   0.        ,          1.4005332 ,  -4.3804708 ,   0.        ,   4.5259585 ],       [  7.5860476 ,   0.        ,  -3.380057  ,  -2.582017  ,          2.8720136 ,  11.115386  ,   8.538795  , -19.424133  ],       [ -3.917915  ,   4.0665693 ,   0.        , -12.9890995 ,          4.1200004 ,   0.        ,  -1.2079337 ,   0.        ],       [  2.170701  , -13.048945  ,   0.14143904, -13.210753  ,          8.728679  ,  21.399652  ,   0.        ,   0.        ],       [ -7.26988   ,   3.2198274 , -19.392447  , -19.767794  ,         15.910901  , -15.649479  ,   5.384444  ,  -3.8574069 ],       [  3.7815158 ,   4.670071  ,   0.        ,   1.1652755 ,         -7.5341015 ,   0.        ,   0.        ,   0.        ],       [  3.5399184 , -16.147419  , -15.11536   ,   0.9096771 ,         12.691319  ,   2.455996  ,   5.0164676 ,  16.101252  ],       [ -7.186151  ,   7.0449085 ,  11.977984  ,  20.375097  ,          6.7509637 ,  15.382088  , -18.239048  ,  -0.90406996]],      dtype=np.float32)
mask = np.asarray([[False,  True, False, False, False, False, False, False],       [False,  True, False,  True, False, False, False, False],       [False, False, False, False,  True,  True, False, False],       [ True,  True, False,  True,  True, False, False, False],       [False, False,  True, False,  True,  True,  True, False],       [False, False, False,  True, False, False,  True, False],       [ True, False, False, False, False,  True,  True, False],       [False,  True, False, False, False,  True,  True,  True],       [False,  True, False,  True, False, False,  True, False],       [False,  True, False, False, False, False, False, False],       [False, False,  True, False, False,  True, False,  True],       [False, False, False, False, False, False,  True,  True],       [False, False, False, False, False, False, False, False],       [False, False,  True, False, False,  True,  True,  True],       [False, False, False, False, False, False, False, False],       [False, False, False, False, False, False, False, False]])
x = mxp.asarray(data, mask=mask)
```

</details>

The repr in this branch is:

<details>

```
<marray.MaskedArray>
Data:
[[10.145273, --, 10.543168, 10.06865, 4.89986, 12.200225, 3.9135966, 1.306433],
 [10.602975, --, -1.5708277, --, -6.0110965, -2.1144137, 13.986411, 0.52917767],
 [-12.671135, 6.484597, -7.1020255, -10.702476, --, --, 9.679424, -2.5499823],
 ...,
 [3.7815158, 4.670071, --, 1.1652755, -7.5341015, --, --, --],
 [3.5399184, -16.147419, -15.11536, 0.9096771, 12.691319, 2.455996, 5.0164676, 16.101252],
 [-7.186151, 7.0449085, 11.977984, 20.375097, 6.7509637, 15.382088, -18.239048, -0.90406996]]
Mask:
[[False  True False False False False False False]
 [False  True False  True False False False False]
 [False False False False  True  True False False]
 [ True  True False  True  True False False False]
 [False False  True False  True  True  True False]
 [False False False  True False False  True False]
 [ True False False False False  True  True False]
 [False  True False False False  True  True  True]
 [False  True False  True False False  True False]
 [False  True False False False False False False]
 [False False  True False False  True False  True]
 [False False False False False False  True  True]
 [False False False False False False False False]
 [False False  True False False  True  True  True]
 [False False False False False False False False]
 [False False False False False False False False]]
```
and the `str` is:
```
[[10.145273, --, 10.543168, 10.06865, 4.89986, 12.200225, 3.9135966, 1.306433],
 [10.602975, --, -1.5708277, --, -6.0110965, -2.1144137, 13.986411, 0.52917767],
 [-12.671135, 6.484597, -7.1020255, -10.702476, --, --, 9.679424, -2.5499823],
 ...,
 [3.7815158, 4.670071, --, 1.1652755, -7.5341015, --, --, --],
 [3.5399184, -16.147419, -15.11536, 0.9096771, 12.691319, 2.455996, 5.0164676, 16.101252],
 [-7.186151, 7.0449085, 11.977984, 20.375097, 6.7509637, 15.382088, -18.239048, -0.90406996]]
```

</details>

In `main`:

<details>

```
MArray(
    array([[ 10.145273  ,   0.        ,  10.543168  ,  10.06865   ,
          4.89986   ,  12.200225  ,   3.9135966 ,   1.306433  ],
       [ 10.602975  ,   0.        ,  -1.5708277 ,   0.        ,
         -6.0110965 ,  -2.1144137 ,  13.986411  ,   0.52917767],
       [-12.671135  ,   6.484597  ,  -7.1020255 , -10.702476  ,
          0.        ,   0.        ,   9.679424  ,  -2.5499823 ],
       [  0.        ,   0.        ,  -5.3532686 ,   0.        ,
          0.        ,  -1.7456701 , -21.932783  ,   2.6757898 ],
       [ -5.968359  , -12.241867  ,   0.        ,  -2.3720222 ,
          0.        ,   0.        ,   0.        ,   0.13664268],
       [-15.532685  ,   2.4078274 ,   6.282031  ,   0.        ,
          7.5855317 ,  20.759636  ,   0.        ,  15.117776  ],
       [  0.        ,   6.4898    ,  -0.9861215 ,   6.929004  ,
         -7.7859383 ,   0.        ,   0.        ,  -7.2034793 ],
       [ 20.820364  ,   0.        ,  -9.436462  ,  -0.99235004,
          8.174761  ,   0.        ,   0.        ,   0.        ],
       [ -3.9510887 ,   0.        ,  -7.876617  ,   0.        ,
          1.4005332 ,  -4.3804708 ,   0.        ,   4.5259585 ],
       [  7.5860476 ,   0.        ,  -3.380057  ,  -2.582017  ,
          2.8720136 ,  11.115386  ,   8.538795  , -19.424133  ],
       [ -3.917915  ,   4.0665693 ,   0.        , -12.9890995 ,
          4.1200004 ,   0.        ,  -1.2079337 ,   0.        ],
       [  2.170701  , -13.048945  ,   0.14143904, -13.210753  ,
          8.728679  ,  21.399652  ,   0.        ,   0.        ],
       [ -7.26988   ,   3.2198274 , -19.392447  , -19.767794  ,
         15.910901  , -15.649479  ,   5.384444  ,  -3.8574069 ],
       [  3.7815158 ,   4.670071  ,   0.        ,   1.1652755 ,
         -7.5341015 ,   0.        ,   0.        ,   0.        ],
       [  3.5399184 , -16.147419  , -15.11536   ,   0.9096771 ,
         12.691319  ,   2.455996  ,   5.0164676 ,  16.101252  ],
       [ -7.186151  ,   7.0449085 ,  11.977984  ,  20.375097  ,
          6.7509637 ,  15.382088  , -18.239048  ,  -0.90406996]],
      dtype=float32),
    array([[False,  True, False, False, False, False, False, False],
       [False,  True, False,  True, False, False, False, False],
       [False, False, False, False,  True,  True, False, False],
       [ True,  True, False,  True,  True, False, False, False],
       [False, False,  True, False,  True,  True,  True, False],
       [False, False, False,  True, False, False,  True, False],
       [ True, False, False, False, False,  True,  True, False],
       [False,  True, False, False, False,  True,  True,  True],
       [False,  True, False,  True, False, False,  True, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False,  True, False,  True],
       [False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False, False],
       [False, False,  True, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])
)
```
vs
```
MArray(
    [[ 10.145273     0.          10.543168    10.06865      4.89986
   12.200225     3.9135966    1.306433  ]
 [ 10.602975     0.          -1.5708277    0.          -6.0110965
   -2.1144137   13.986411     0.52917767]
 [-12.671135     6.484597    -7.1020255  -10.702476     0.
    0.           9.679424    -2.5499823 ]
 [  0.           0.          -5.3532686    0.           0.
   -1.7456701  -21.932783     2.6757898 ]
 [ -5.968359   -12.241867     0.          -2.3720222    0.
    0.           0.           0.13664268]
 [-15.532685     2.4078274    6.282031     0.           7.5855317
   20.759636     0.          15.117776  ]
 [  0.           6.4898      -0.9861215    6.929004    -7.7859383
    0.           0.          -7.2034793 ]
 [ 20.820364     0.          -9.436462    -0.99235004   8.174761
    0.           0.           0.        ]
 [ -3.9510887    0.          -7.876617     0.           1.4005332
   -4.3804708    0.           4.5259585 ]
 [  7.5860476    0.          -3.380057    -2.582017     2.8720136
   11.115386     8.538795   -19.424133  ]
 [ -3.917915     4.0665693    0.         -12.9890995    4.1200004
    0.          -1.2079337    0.        ]
 [  2.170701   -13.048945     0.14143904 -13.210753     8.728679
   21.399652     0.           0.        ]
 [ -7.26988      3.2198274  -19.392447   -19.767794    15.910901
  -15.649479     5.384444    -3.8574069 ]
 [  3.7815158    4.670071     0.           1.1652755   -7.5341015
    0.           0.           0.        ]
 [  3.5399184  -16.147419   -15.11536      0.9096771   12.691319
    2.455996     5.0164676   16.101252  ]
 [ -7.186151     7.0449085   11.977984    20.375097     6.7509637
   15.382088   -18.239048    -0.90406996]],
    [[False  True False False False False False False]
 [False  True False  True False False False False]
 [False False False False  True  True False False]
 [ True  True False  True  True False False False]
 [False False  True False  True  True  True False]
 [False False False  True False False  True False]
 [ True False False False False  True  True False]
 [False  True False False False  True  True  True]
 [False  True False  True False False  True False]
 [False  True False False False False False False]
 [False False  True False False  True False  True]
 [False False False False False False  True  True]
 [False False False False False False False False]
 [False False  True False False  True  True  True]
 [False False False False False False False False]
 [False False False False False False False False]]
)
```

</details>

And `np.ma.masked_array`:

<details>

```
masked_array(
  data=[[10.145273208618164, --, 10.543168067932129, 10.068650245666504,
         4.89985990524292, 12.200224876403809, 3.9135966300964355,
         1.3064329624176025],
        [10.602974891662598, --, -1.5708277225494385, --,
         -6.011096477508545, -2.1144137382507324, 13.986411094665527,
         0.5291776657104492],
        [-12.671134948730469, 6.484597206115723, -7.102025508880615,
         -10.702475547790527, --, --, 9.679424285888672,
         -2.5499823093414307],
        [--, --, -5.353268623352051, --, --, -1.7456700801849365,
         -21.932783126831055, 2.6757898330688477],
        [-5.968358993530273, -12.241867065429688, --,
         -2.3720221519470215, --, --, --, 0.1366426795721054],
        [-15.532685279846191, 2.407827377319336, 6.282031059265137, --,
         7.585531711578369, 20.75963592529297, --, 15.117775917053223],
        [--, 6.489799976348877, -0.9861214756965637, 6.929004192352295,
         -7.785938262939453, --, --, -7.203479290008545],
        [20.820363998413086, --, -9.43646240234375, -0.9923500418663025,
         8.174760818481445, --, --, --],
        [-3.9510886669158936, --, -7.876616954803467, --,
         1.4005331993103027, -4.3804707527160645, --, 4.52595853805542],
        [7.586047649383545, --, -3.3800570964813232, -2.582016944885254,
         2.872013568878174, 11.115386009216309, 8.538795471191406,
         -19.42413330078125],
        [-3.917915105819702, 4.0665693283081055, --, -12.989099502563477,
         4.12000036239624, --, -1.2079336643218994, --],
        [2.170701026916504, -13.048945426940918, 0.1414390355348587,
         -13.210753440856934, 8.728678703308105, 21.3996524810791, --,
         --],
        [-7.2698798179626465, 3.21982741355896, -19.392446517944336,
         -19.767793655395508, 15.910901069641113, -15.649478912353516,
         5.384444236755371, -3.8574068546295166],
        [3.7815158367156982, 4.670071125030518, --, 1.1652754545211792,
         -7.534101486206055, --, --, --],
        [3.5399184226989746, -16.147418975830078, -15.115360260009766,
         0.9096770882606506, 12.691319465637207, 2.455996036529541,
         5.016467571258545, 16.10125160217285],
        [-7.186151027679443, 7.04490852355957, 11.977984428405762,
         20.375097274780273, 6.7509636878967285, 15.382087707519531,
         -18.23904800415039, -0.9040699601173401]],
  mask=[[False,  True, False, False, False, False, False, False],
        [False,  True, False,  True, False, False, False, False],
        [False, False, False, False,  True,  True, False, False],
        [ True,  True, False,  True,  True, False, False, False],
        [False, False,  True, False,  True,  True,  True, False],
        [False, False, False,  True, False, False,  True, False],
        [ True, False, False, False, False,  True,  True, False],
        [False,  True, False, False, False,  True,  True,  True],
        [False,  True, False,  True, False, False,  True, False],
        [False,  True, False, False, False, False, False, False],
        [False, False,  True, False, False,  True, False,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False, False, False],
        [False, False,  True, False, False,  True,  True,  True],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False]],
  fill_value=np.float64(1e+20),
  dtype=float32)
```
vs
```
[[10.145273208618164 -- 10.543168067932129 10.068650245666504
  4.89985990524292 12.200224876403809 3.9135966300964355
  1.3064329624176025]
 [10.602974891662598 -- -1.5708277225494385 -- -6.011096477508545
  -2.1144137382507324 13.986411094665527 0.5291776657104492]
 [-12.671134948730469 6.484597206115723 -7.102025508880615
  -10.702475547790527 -- -- 9.679424285888672 -2.5499823093414307]
 [-- -- -5.353268623352051 -- -- -1.7456700801849365 -21.932783126831055
  2.6757898330688477]
 [-5.968358993530273 -12.241867065429688 -- -2.3720221519470215 -- -- --
  0.1366426795721054]
 [-15.532685279846191 2.407827377319336 6.282031059265137 --
  7.585531711578369 20.75963592529297 -- 15.117775917053223]
 [-- 6.489799976348877 -0.9861214756965637 6.929004192352295
  -7.785938262939453 -- -- -7.203479290008545]
 [20.820363998413086 -- -9.43646240234375 -0.9923500418663025
  8.174760818481445 -- -- --]
 [-3.9510886669158936 -- -7.876616954803467 -- 1.4005331993103027
  -4.3804707527160645 -- 4.52595853805542]
 [7.586047649383545 -- -3.3800570964813232 -2.582016944885254
  2.872013568878174 11.115386009216309 8.538795471191406
  -19.42413330078125]
 [-3.917915105819702 4.0665693283081055 -- -12.989099502563477
  4.12000036239624 -- -1.2079336643218994 --]
 [2.170701026916504 -13.048945426940918 0.1414390355348587
  -13.210753440856934 8.728678703308105 21.3996524810791 -- --]
 [-7.2698798179626465 3.21982741355896 -19.392446517944336
  -19.767793655395508 15.910901069641113 -15.649478912353516
  5.384444236755371 -3.8574068546295166]
 [3.7815158367156982 4.670071125030518 -- 1.1652754545211792
  -7.534101486206055 -- -- --]
 [3.5399184226989746 -16.147418975830078 -15.115360260009766
  0.9096770882606506 12.691319465637207 2.455996036529541
  5.016467571258545 16.10125160217285]
 [-7.186151027679443 7.04490852355957 11.977984428405762
  20.375097274780273 6.7509636878967285 15.382087707519531
  -18.23904800415039 -0.9040699601173401]]
```

</details>

And the hack from gh-12:

<details>


```
array([[ 10.145273  ,  ---        ,  10.543168  ,  10.06865   ,
          4.89986   ,  12.200225  ,   3.9135966 ,   1.306433  ],
       [ 10.602975  ,  ---        ,  -1.5708277 ,  ---        ,
         -6.0110965 ,  -2.1144137 ,  13.986411  ,   0.52917767],
       [-12.671135  ,   6.484597  ,  -7.1020255 , -10.702476  ,
         ---        ,  ---        ,   9.679424  ,  -2.5499823 ],
       [ ---        ,  ---        ,  -5.3532686 ,  ---        ,
         ---        ,  -1.7456701 , -21.932783  ,   2.6757898 ],
       [ -5.968359  , -12.241867  ,  ---        ,  -2.3720222 ,
         ---        ,  ---        ,  ---        ,   0.13664268],
       [-15.532685  ,   2.4078274 ,   6.282031  ,  ---        ,
          7.5855317 ,  20.759636  ,  ---        ,  15.117776  ],
       [ ---        ,   6.4898    ,  ---9861215 ,   6.929004  ,
         -7.7859383 ,  ---        ,  ---        ,  -7.2034793 ],
       [ 20.820364  ,  ---        ,  -9.436462  ,  ---99235004,
          8.174761  ,  ---        ,  ---        ,  ---        ],
       [ -3.9510887 ,  ---        ,  -7.876617  ,  ---        ,
          1.4005332 ,  -4.3804708 ,  ---        ,   4.5259585 ],
       [  7.5860476 ,  ---        ,  -3.380057  ,  -2.582017  ,
          2.8720136 ,  11.115386  ,   8.538795  , -19.424133  ],
       [ -3.917915  ,   4.0665693 ,  ---        , -12.9890995 ,
          4.1200004 ,  ---        ,  -1.2079337 ,  ---        ],
       [  2.170701  , -13.048945  ,   0.14143904, -13.210753  ,
          8.728679  ,  21.399652  ,  ---        ,  ---        ],
       [ -7.26988   ,   3.2198274 , -19.392447  , -19.767794  ,
         15.910901  , -15.649479  ,   5.384444  ,  -3.8574069 ],
       [  3.7815158 ,   4.670071  ,  ---        ,   1.1652755 ,
         -7.5341015 ,  ---        ,  ---        ,  ---        ],
       [  3.5399184 , -16.147419  , -15.11536   ,   0.9096771 ,
         12.691319  ,   2.455996  ,   5.0164676 ,  16.101252  ],
       [ -7.186151  ,   7.0449085 ,  11.977984  ,  20.375097  ,
          6.7509637 ,  15.382088  , -18.239048  ,  ---90406996]],
      dtype=float32)
```
vs
```
[[ 10.145273    ---          10.543168    10.06865      4.89986
   12.200225     3.9135966    1.306433  ]
 [ 10.602975    ---          -1.5708277   ---          -6.0110965
   -2.1144137   13.986411     0.52917767]
 [-12.671135     6.484597    -7.1020255  -10.702476    ---
   ---           9.679424    -2.5499823 ]
 [ ---          ---          -5.3532686   ---          ---
   -1.7456701  -21.932783     2.6757898 ]
 [ -5.968359   -12.241867    ---          -2.3720222   ---
   ---          ---           0.13664268]
 [-15.532685     2.4078274    6.282031    ---           7.5855317
   20.759636    ---          15.117776  ]
 [ ---           6.4898      ---9861215    6.929004    -7.7859383
   ---          ---          -7.2034793 ]
 [ 20.820364    ---          -9.436462    ---99235004   8.174761
   ---          ---          ---        ]
 [ -3.9510887   ---          -7.876617    ---           1.4005332
   -4.3804708   ---           4.5259585 ]
 [  7.5860476   ---          -3.380057    -2.582017     2.8720136
   11.115386     8.538795   -19.424133  ]
 [ -3.917915     4.0665693   ---         -12.9890995    4.1200004
   ---          -1.2079337   ---        ]
 [  2.170701   -13.048945     0.14143904 -13.210753     8.728679
   21.399652    ---          ---        ]
 [ -7.26988      3.2198274  -19.392447   -19.767794    15.910901
  -15.649479     5.384444    -3.8574069 ]
 [  3.7815158    4.670071    ---           1.1652755   -7.5341015
   ---          ---          ---        ]
 [  3.5399184  -16.147419   -15.11536      0.9096771   12.691319
    2.455996     5.0164676   16.101252  ]
 [ -7.186151     7.0449085   11.977984    20.375097     6.7509637
   15.382088   -18.239048    ---90406996]]
```

</details>

Just writing this out so they're easy-ish to compare.

**Pull request closed without merging**
